# Generated by Django 5.2.7 on 2025-10-14 19:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transition',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transition_type',
            new_name='transaction_type',
        ),
    ]
